send and accept invitation
Zummit-Africa-Inc/zapi-lambda-core pull request #104
Opened 2022-11-10 10:30 UTC by SunmadeBabafemi

1. an invitation entity was created
2. a user can send an invite to another user's email to become a contributor to his api
3. the invitee will only have yo click the accept link in his email to accept the invite
4. the invitation only lasts for 30 days
5. after accepting the invite the corresponding model gets deleted from the database

2022-11-10 11:43 UTC, Chimexx commented
Seen, I have some observations... I will review later today.

2022-11-10 22:51 UTC, Chimexx requested changes
Nice, just a few more changes

2022-11-10 22:51 UTC, Chimexx commented on src/api/api.controller.ts
> +  async getApiContributors(
Add IdCheck guard here to verify if apiId exists in the db,
Also call the Authorization and Authentication guard if needed.

2022-11-10 22:51 UTC, Chimexx commented on src/api/api.service.ts
> +      }
If you added IdCheck guard, there won't be need to check if api exists here or any other place.

2022-11-10 22:51 UTC, Chimexx commented on src/api/api.service.ts
> +      return contributors
I would do this instead 
![image](https://user-images.githubusercontent.com/84224449/201221072-5cbc0923-d1ab-4607-97af-bc1301daec45.png)

2022-11-10 22:51 UTC, Chimexx commented on src/invitation/invitation.service.ts
> +        throw new BadRequestException(
remove logger

2022-11-10 22:51 UTC, Chimexx commented on src/invitation/invitation.service.ts
> +          )
Again, Idcheck guard prevents this.

2022-11-10 22:51 UTC, Chimexx commented on src/invitation/invitation.service.ts
> +      await this.invitationRepo.delete(existingInvite.id)
This should be synchronous

2022-11-10 22:51 UTC, Chimexx commented on src/invitation/invitation.service.ts
> +      // } else {
Remove if not needed

2022-11-11 09:02 UTC, SunmadeBabafemi commented on src/invitation/invitation.service.ts
> +      await this.invitationRepo.delete(existingInvite.id)
thanks boss... i'll get to it

2022-11-14 08:26 UTC, johnayinde requested changes

2022-11-14 08:26 UTC, johnayinde commented on src/invitation/invitation.controller.ts
> +  @IdCheck('apiId')
You can use one Idcheck instead separated with commas

2022-11-15 07:38 UTC, Chimexx reviewed
What of Authentication guard? Any one without a token can access these endpoints, unless you plan to make them public

2022-11-15 08:55 UTC, SunmadeBabafemi commented
> What of Authentication guard? Any one without a token can access these endpoints, unless you plan to make them public

i just added guards to the send invite and view invitees.... for accepting the invite, the endpoint is hit from the invitee's email.. there is no guard that can be inserted there

2022-11-15 09:31 UTC, merged