implemented contact us feature
Zummit-Africa-Inc/zapi-lambda-core pull request #143
Opened 2023-02-02 18:48 UTC by johnayinde

2023-02-03 00:13 UTC, Chimexx requested changes
Looks Good, except the migration file

2023-02-03 00:13 UTC, Chimexx commented on src/database/migration/1675362826180-contactUs.ts
> +    await queryRunner.query(
Remove Cat entity stuff from the migration file

2023-02-04 00:20 UTC, Chimexx approved these changes

2023-02-07 08:54 UTC, PhilemonBrain approved these changes

2023-02-07 08:55 UTC, merged