User-apis
Zummit-Africa-Inc/zapi-lambda-core pull request #22
Opened 2022-09-13 10:19 UTC by danifara3

added Endpoint to get all APIs belonging to a user

Endpoint to Add an `Endpoint` to an API (C-S)

2022-09-13 12:50 UTC, Chimexx requested changes
I believe your task is to create endpoint to add 'endpoints' to an api

You should be working in endpoints folder, not api

2022-09-13 21:11 UTC, danifara3 commented
i was the two task below

added Endpoint to get all APIs belonging to a user

Endpoint to Add an Endpoint to an API (C-S)

2022-09-14 08:04 UTC, PhilemonBrain commented
@johnayinde seems like dan already worked on a feature i assigned to you. Please review this PR

2022-09-14 09:38 UTC, PhilemonBrain approved these changes

2022-09-14 09:38 UTC, merged