edit an API
Zummit-Africa-Inc/zapi-lambda-core pull request #31
Opened 2022-09-16 08:35 UTC by johnayinde

- added **logo_url, api_website and term_of_use**  columns  to entity file
- 
- create DTO file showing all the optional columns that can be updated on the API Table
- Generated migration file for the updated entity

2022-09-16 20:19 UTC, Chimexx commented
![image](https://user-images.githubusercontent.com/84224449/190726008-4ba4ae0c-44c2-4c4f-a3b4-ee84d9f0f468.png)
This is what I get, if it works fine on your end, I'll like to see a screenshot

2022-09-17 17:36 UTC, johnayinde commented
> ![image](https://user-images.githubusercontent.com/84224449/190726008-4ba4ae0c-44c2-4c4f-a3b4-ee84d9f0f468.png) This is what I get, if it works fine on your end, I'll like to see a screenshot

2022-09-17 17:41 UTC, johnayinde commented
@Chimexx 
![apiNAme](https://user-images.githubusercontent.com/38318744/190869553-e2b66c53-a7ad-4470-b15a-c95682aeb4b3.PNG)

![category](https://user-images.githubusercontent.com/38318744/190869555-25b4a926-358a-4ef2-9f52-afebac0555a2.PNG)

you probably used a wrongly  formatted UUID string
 try and change the first or any number/character in a valid ID to a wrong one

2022-09-17 18:56 UTC, Chimexx requested changes

2022-09-17 18:56 UTC, Chimexx commented on src/api/api.service.ts
> +          throw new NotFoundException(
You haven't fixed this, it should be BadRequestException

2022-09-17 18:56 UTC, Chimexx commented on src/api/api.service.ts
> +          throw new NotFoundException(
What will be the effect of this block of code assuming the user isn't updating the category? This should only run if the user is updating category too

2022-09-17 18:56 UTC, Chimexx commented on src/api/api.service.ts
> +          where: { name: updateApiDto.name },
You don't have to check category name, what you are updating is api not category

2022-09-17 18:56 UTC, Chimexx commented on src/api/api.service.ts
> +            ZaLaResponse.BadRequest(
This block of code forces the user to update the category whether he likes it or not. rremove it.

2022-09-17 19:09 UTC, Chimexx commented on src/api/api.service.ts
> +          );
What will be the effect of this block of code assuming the user isn't updating the category? This should only run if the user is updating category too

2022-09-17 19:12 UTC, Chimexx commented on src/api/api.service.ts
> +          );
This block of code forces the user to change the api name whether he likes it or not. rremove it.

2022-09-17 20:39 UTC, SunmadeBabafemi requested changes

2022-09-17 20:39 UTC, SunmadeBabafemi commented on src/api/api.service.ts
> +        console.log(updateApiDto.name);
anytime you use console.logs for debugging and the likes try to clean it up before pushing it...

2022-09-18 19:27 UTC, PhilemonBrain submitted a review, later dismissed

2022-09-19 04:14 UTC, PhilemonBrain approved these changes

2022-09-19 04:14 UTC, merged