create endpoint architecture
Zummit-Africa-Inc/zapi-lambda-core pull request #4
Opened 2022-08-29 09:12 UTC by Oladimejiibitoye

This includes the Entity schema, module structure( controller, service, etc files), relationship with other entity schemas

2022-08-30 00:57 UTC, TijanAyo commented
LGTM 

Did you run migrations tho... to test if the table is being created properly?

2022-08-30 09:18 UTC, PhilemonBrain requested changes
no migration file

2022-08-31 08:03 UTC, johnayinde approved these changes

2022-08-31 09:14 UTC, PhilemonBrain approved these changes

2022-08-31 09:14 UTC, merged