Pricing structure
Zummit-Africa-Inc/zapi-lambda-core pull request #9
Opened 2022-08-30 19:48 UTC by TijanAyo

The architecture of the `Pricing` feature

2022-08-31 16:14 UTC, SunmadeBabafemi approved these changes

2022-09-01 08:41 UTC, Chimexx approved these changes

2022-09-01 08:48 UTC, PhilemonBrain requested changes

2022-09-01 08:48 UTC, PhilemonBrain commented on src/database/migration/1661888425310-pricingEntity.ts
> +
why are u altering the table? has the table been created b4?

2022-09-01 09:28 UTC, PhilemonBrain approved these changes

2022-09-01 09:28 UTC, merged